### ISSUE TITLE
可以提供一个新手安装教程吗？

### ISSUE THREAD

**Issue by DyNooob** [HullQin/poker#1]
看到这个仓库是使用Python写的很开心，因为自己也是在用Python。最近也想研究网页方面的小游戏。但是关于docker这方面真的不太熟，可以说是零，自己尝试安装后出现如下几个问题：

1. 前端代码生成build文件夹下有一个static以及其他网页文件，但是后端仓库根目录没有static，所以是是直接把build文件复制到后端的根目录中？
2. 使用 docker run的时候成功了，但是通过docker ps发现运行在8000端口，但是我访问不通(远程服务器部署，端口策略已通过
3. 如果需要通过80的某个目录访问，我使用了nginx反向代理，但是出502，服务器本地使用 curl 8000端口出现被拒绝的情况。

所以我感觉我一开始就部署错了，麻烦您花点时间可以写一个小白级别的部署教程😁
再次感谢您了！

**Comment by HullQin** [comment]
感谢关注。
1. 可以不用Docker，忽略相关文件即可。你的情况，估计是因为没搞懂Docker的网络策略，可以在docker run时加一个参数`--network host`。
2. 如果不用Docker，在你安装好daphne依赖后，项目根目录下，直接运行`daphne -b 0.0.0.0 -p 8000 server:application`来启动服务，服务会在8000端口。

**Comment by HullQin** [comment]
噢，上面回答了问题2和3。还有问题1:
是把build文件夹复制到后端目录，并且把build文件夹名字改为static。

**Comment by DyNooob** [comment]
👌🏻 十分感谢回复！
